### ISSUE TITLE
[Serverless] make layer with Serverless and use it with `Ref:`

### ISSUE THREAD

**Issue by siruku6** [siruku6/fx_alarm_py#142]
like this

```yaml
layers:
  test:
    path: layer
functions:
  hello:
    handler: handler.hello
    layers:
      - { Ref: TestLambdaLayer }
```

- References
https://www.serverless.com/framework/docs/providers/aws/guide/layers
