### ISSUE TITLE
Fix: net::ERR_FAILED 502

### ISSUE THREAD

**Issue by siruku6** [siruku6/fx_alarm_py#197]
Sometimes API Gateway respond the error 502.

Save the log of API Gateway and fix this error.

**Comment by siruku6** [comment]
# How to save log of API Gateway 

https://forum.serverless.com/t/how-to-setup-custom-access-logging-for-api-gateway-using-serverless/3288/2

with CloudFormation
```
resources:
  Resources:
     ApiGatewayStage:
      Type: AWS::ApiGateway::Stage
      Properties:
        AccessLogSetting:
          Format: "String"
          DestinationArn: "String"
```

For example

```
      AccessLogSetting:
        DestinationArn: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${ServiceName}-hoge'
        Format: '$context.requestId $context.identity.sourceIp $context.identity.caller  $context.identity.user [$context.requestTime] "$context.httpMethod $context.resourcePath $context.protocol" $context.status $context.responseLength $context.requestId'
```
